# Generated by Django 4.1 on 2022-09-25 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60, unique=True, verbose_name='Nombre')),
                ('duracion', models.IntegerField()),
                ('precio', models.IntegerField()),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
