# Generated by Django 4.1 on 2022-09-25 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eps',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True, verbose_name='Nombre')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
